### ISSUE TITLE
Mobile tick marks not reducing line chart

### ISSUE THREAD

**Issue by cathhanrahan** [abcnews/dailygraphics#82] opened 2017-07-04 06:09 UTC
Hi guys. I am trying to reduce the number of mobile tick marks in my line chart but it is not responding when the date format is 'x' rather than date. I've tried to reduce my 'mobileTicksX' to 2 but it isn't responding. Thanks, Cath.

**Comment by phocks** [comment] 2017-07-04 23:08
Hi @cathhanrahan, Matt just spoke to me about this and I will have a look. If you could show me the exact data you're trying to put in that could help me out trying to debug. Thanks, Josh.

**Comment by cathhanrahan** [comment] 2017-07-04 23:10
Hi Josh. Here's a link to the Chartbuilder chart I am looking at. Can you access it? Thanks, Cath.
http://newsdev3.aus.aunty.abc.net.au/tools/chart-builder/graphics/religionbyage040717/build/

**Comment by phocks** [comment] 2017-07-04 23:26
Thanks Cath, yes I can see the x values are clumping together on mobile. And this doesn't happen when they are dates and the mobileTicksX value is set to 2 etc. I will have a look at the code and see if I can find out what's happening. Hold tight.

**Comment by phocks** [comment] 2017-07-05 00:33
Hi Cath, okay so I have found where the issue is and I think I have a solution potentially. It's worth noting that this functionality is built into the line chart anyway it seems as I just saw this in the documentation:

> ticksX
> Default: 10
> Approximate number of ticks to show on the X axis. Only applies to date-based line charts. Otherwise every x value has a tick.

So if it's not a date based x axis it will not even try to reduce the number of ticks anyway in the code. I think I have a way of making it work though. Give me a bit of time to test another way of doing it so the x axis isn't squashed at the bottom on mobile.

**Comment by phocks** [comment] 2017-07-05 01:12
OK! So the problem comes about due to the way D3 scales the data for axis. With date ranges and "linear" (1 - 100) ranges it handles it fine, but for "ordinal" or discrete ranges [kids, teenagers, adults, seniors] it has trouble working out which ones to display or cut out, so it just displays them all.

Fortunately it looks like we can just tell it which ticks we want to be displayed as documented with the `tickValuesX` which lets us choose which values to display on the x axis. I'll update the documentation to show that this should accept a comma separated list of values.

So from this I have programmed into the line chart a new LABEL named `mobileTickValuesX` which will also accept a comma separated list of values. This will ensure only these values display when on mobile view.

Here is an example:

![snip20170705_1](https://user-images.githubusercontent.com/437566/27845327-b8a405e6-6171-11e7-92d2-311c7b0121e2.png)

14 values are displayed on Desktop. And now I set `mobileTickValuesX` to `2, 4, 6, 8, 10, 12, 14` in the Google Doc data. And we should get this on Mobile view:

![snip20170705_2](https://user-images.githubusercontent.com/437566/27845350-ec43f6e0-6171-11e7-9a88-98cabe199838.png)

As you can see only the even numbers are showing. I should have probably not used numbers in this example as they are actually being treated as text strings. So in your data you will set `mobileTickValuesX` to something like `0-14, 25-34, 45-54, 65-74, 85 years` to achieve a similar result.

I'll need to review this code with the guys and push the changes before this will work, but this seems like it will fix the issue for the time being. 

We may be able to figure out a way to make this process more automatic and get the system to automatically detect which ticks to display and which to hide on mobile view.

**Comment by cathhanrahan** [comment] 2017-07-05 01:30
Ok that sounds great Josh. Let me know when it is functional and I'll give it a try. Cath.

**Comment by phocks** [comment] 2017-07-05 02:02
Found a bug. Looks like it's not liking the 0-14, 25-34, 45-54, 65-74, 85 years values. I'll check what's going on. Something strange!

**Comment by phocks** [comment] 2017-07-05 02:54
We have merged the changes and you should be able to give it a try now. You may need to rebuild your template from within Chart Builder. I have altered this chart with changes for testing. See if it is behaving as you expect. http://newsdev3.aus.aunty.abc.net.au/tools/chart-builder/graphics/religionbyage040717/build/

**Comment by cathhanrahan** [comment] 2017-07-05 03:08
Thanks so much Josh. It looks great now.

**Closed as completed** 2017-07-07 00:34 UTC
Labels: bug
